"""
Django settings for KHCompounds_database project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

#import sys
#sys.path.append(' c:\\users\\bid2\\envs\\django_database_project\\lib\\site-packages\\openbabel')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x&)3mpuk($ydy)@e1882htn(pb0)-6-wdgs$ju#rhh34ymfo$='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Add the moleculesdb app
    'moleculesdb.apps.MoleculesdbConfig',
    'django_crontab',
    'jazzmin',
    'forms_fieldset',
    'dbbackup',  # django-dbbackup
    'labmembers', #user logins
    'crispy_forms',
    'crispy_bootstrap5',
    'django_extensions',
    #'backup',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',   # Django auto logout (1)
]

ROOT_URLCONF = 'KHCompounds_database.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django_auto_logout.context_processors.auto_logout_client', #django auto logout(2)
            ],
        },
    },
]

WSGI_APPLICATION = 'KHCompounds_database.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'moleculesdb',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost', #Newly added because of the backup
        'PORT': '5432', #Newly added because of the backup

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    )

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#LOGIN_URL = 'labmembers:login_user'
#LOGIN_URL = 'labmembers:logout'

LOGIN_REDIRECT_URL = 'index'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

#BACKUP_ROOT = '/backup/'
#BACKUP_ROOT = os.path.join(BASE_DIR, 'backup')

#Only used for the debuging, could change during production
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': 'C:\\Users\\bid2\\Desktop\\Projects\\KHCompounds_database\\backup'}

DBBACKUP_EXTENSION = 'pgdump' 

CRONJOBS = [
    ('*/1 * * * *', 'KHCompounds_database.cron.my_backup')
]


#Django session timeout (4)
AUTO_LOGOUT = {'IDLE_TIME': 600, 'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
 'MESSAGE': 'Your session as manager has expired. Please login again to continue.',
 } # time is in seconds


#On the server it will be stored as FTP, this is how you go about it
#pip install django-storages
#DBBACKUP_STORAGE = 'storages.backends.ftp.FTPStorage
#DBBACKUP_STORAGE_OPTIONS = {
 #   'location': 'ftp://user:pass@server:21'
#}
#https://django-dbbackup.readthedocs.io/en/master/storage.html


#cron-tab -- for linux and mac platforms
# Written the scheduled script in cron.py. Need to revise the time to every two weeks
#python manage.py crontab add  : final commands
#python manage.py crontab show
